const cartActionsTypes = {
    START_ADD_TO_CART: "ADD_TO_CART",
    SUCCESS_ADD_TO_CART: "SUCCESS_ADD_TO_CART",
    FAILURE_ADD_TO_CART: "FAILURE_ADD_TO_CART",
    START_REMOVE_FROM_CART: "START_REMOVE_FROM_CART",
    SUCCESS_REMOVE_FROM_CART: "SUCCESS_REMOVE_FROM_CART",
    FAILURE_REMOVE_FROM_CART: "FAILURE_REMOVE_FROM_CART",
    START_FETCH_CART: "START_FETCH_CART",
    SUCCESS_FETCH_CART: "SUCCESS_FETCH_CART",
    FAILURE_FETCH_CART: "FAILURE_FETCH_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART"
}

export default cartActionsTypes