const orderActionsTypes = {
    ADD_ADDRESS: 'ADD_ADDRESS',
    PAYMENT_METHOD: 'PAYMENT_METHOD',
    START_REQUEST_ORDER: 'START_REQUEST_ORDER',
    SUCCESS_REQUEST_ORDER: 'SUCCESS_REQUEST_ORDER',
    FAILURE_REQUEST_ORDER: 'FAILURE_REQUEST_ORDER',
    START_FETCH_ORDER: 'START_FETCH_ORDER',
    SUCCESS_FETCH_ORDER: 'SUCCESS_FETCH_ORDER',
    FAILURE_FETCH_ORDER: 'FAILURE_FETCH_ORDER'
}

export default orderActionsTypes