const productsActionsTypes = {
    PRODUCTS_FETCHING_START: 'PRODUCTS_FETCHING_START',
    PRODUCTS_FETCHING_SUCCESS: 'PRODUCTS_FETCHING_SUCCESS',
    PRODUCTS_FETCHING_FAILURE: 'PRODUCTS_FETCHING_FAILURE',
    PRODUCT_FETCHING_START: 'PRODUCT_FETCHING_START',
    PRODUCT_FETCHING_SUCCESS: 'PRODUCT_FETCHING_SUCCESS',
    PRODUCT_FETCHING_FAILURE: 'PRODUCT_FETCHING_FAILURE',
    START_REMOVE_PRODUCT: 'START_REMOVE_PRODUCT',
    SUCCESS_REMOVE_PRODUCT: 'SUCCESS_REMOVE_PRODUCT',
    FAILURE_REMOVE_PRODUCT: 'FAILURE_REMOVE_PRODUCT',
    START_CREATE_PRODUCT: 'START_CREATE_PRODUCT',
    SUCCESS_CREATE_PRODUCT: 'SUCCESS_CREATE_PRODUCT',
    FAILURE_CREATE_PRODUCT: 'FAILURE_CREATE_PRODUCT',
    START_CREATE_REVIEW: 'START_CREATE_REVIEW',
    SUCCESS_CREATE_REVIEW: 'SUCCESS_CREATE_REVIEW',
    FAILURE_CREATE_REVIEW: 'FAILURE_CREATE_REVIEW'
}

export default productsActionsTypes