const userActionsTypes = {
    USER_LOGIN_START: 'USER_LOGIN_START',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_REGISTER_START: 'USER_REGISTER_START',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    REQUEST_USER_START: 'REQUEST_USER_PROFILE',
    REQUEST_USER_SUCCESS: 'REQUEST_USER_SUCCESS',
    REQUEST_USER_FAILURE: 'REQUEST_USER_FAILURE',
    LOGOUT: 'LOGOUT'
}

export default userActionsTypes